In [5]:
import numpy as np
import sys

In [2]:
a = [1,2,3,4,5]
b = np.array([1,2,3,4,5])

In [3]:
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [6]:
sys.getsizeof(a)

104

In [7]:
b.nbytes

20

In [9]:
#Array 1D

d1 = np.array([1,2,3])
print(d1)
print(d1.shape)
print(d1.ndim)
print(d1.dtype)

[1 2 3]
(3,)
1
int32


In [10]:
#Array 2D

d2 = np.array([[1,2,3],[4,5,6]])
print(d2)
print(d2.shape)
print(d2.ndim)
print(d2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [13]:
#Array 3D

d3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d3)
print(d3.shape)
print(d3.ndim)
print(d3.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3
int32


In [14]:
result = np.add(a,b)
print(result)

[ 2  4  6  8 10]


In [16]:
print(d2[1,2])
print(d2[0,:])
print(d2[:,2])

6
[1 2 3]
[3 6]
